#!/usr/bin/env bash
#
# setup.sh — one-shot workspace bootstrap for the Playwright testing HUB (starlabs-e2e-tests).
#
# The hub is the workspace root. This wires the targets-under-test into the hub as gitignored symlinks and
# stages the emulator config, so `scripts/run-isolated.sh` (and the dev CLI) can drive a chosen app + CF.
#
# Inputs (env vars; a new dev gets these from the repo's Git secrets / a local .env — see README):
#   APP_PATH        absolute path to the Angular app checkout (REQUIRED)        → symlinked as ./app
#   CF_PATH         absolute path to the cloud-function checkout (REQUIRED)     → symlinked as ./starlabs-cloud-function
#   FLUTTER_PATH    absolute path to the Flutter app checkout (optional)        → symlinked as ../breakthroughs-flutter (bridge location)
#   STARLABS_CICD_SA  path to the starlabs-cicd service-account JSON (optional) → copied to ./starlabs-cicd-sa.json (gitignored)
#
# Firebase TEST project is ALWAYS starlabs-cicd (emulator-intercepted). Run the suite after this with:
#   APP_PATH=<...> EMU_REUSE_APP=1 bash scripts/run-isolated.sh           # (or `npm run report:emulator`)
set -euo pipefail
HUB="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

link() { # $1=target dir  $2=link path  $3=label
  [ -n "$1" ] || { echo "::error::$3 path not set"; return 1; }
  [ -d "$1" ] || { echo "::error::$3 path does not exist: $1"; return 1; }
  ln -sfn "$1" "$2"; echo "✓ $3: $2 -> $1"
}

echo "→ hub = $HUB | test Firebase project = starlabs-cicd (emulator-intercepted)"

# 0) RESOLVE targets from the registry (targets.json, keyed by REPO NAME). Env vars still win, so CI / a dev
#    can override per-run. With one target per type the registry resolves them automatically; add more repos
#    by adding registry lines (addressed by name — no collisions).
TARGETS_BIN="$HUB/bin/targets.cjs"
if [ -f "$HUB/targets.json" ]; then
  APP_PATH="${APP_PATH:-$(node "$TARGETS_BIN" path --type angular 2>/dev/null || true)}"
  CF_PATH="${CF_PATH:-$(node "$TARGETS_BIN" path --type cloud-function 2>/dev/null || true)}"
  FLUTTER_PATH="${FLUTTER_PATH:-$(node "$TARGETS_BIN" path --type flutter 2>/dev/null || true)}"
  # name-keyed symlinks for EVERY registered repo → ./targets/<repo-name> (the multi-target addressing layer)
  mkdir -p "$HUB/targets"
  for n in $(node "$TARGETS_BIN" names 2>/dev/null || true); do
    p="$(node "$TARGETS_BIN" path --name "$n" 2>/dev/null || true)"; [ -n "$p" ] && [ -d "$p" ] && ln -sfn "$p" "$HUB/targets/$n" && echo "✓ target: targets/$n -> $p"
  done
else
  echo "ℹ️  no targets.json — using APP_PATH/CF_PATH/FLUTTER_PATH from env (copy targets.example.json → targets.json to register repos by name)"
fi

# 1) canonical single-target symlinks the scripts resolve (./app, ./starlabs-cloud-function)
[ -n "${APP_PATH:-}" ] || { echo "::error::no Angular target — set APP_PATH or add an angular entry to targets.json"; exit 1; }
[ -n "${CF_PATH:-}"  ] || { echo "::error::no cloud-function target — set CF_PATH or add a cloud-function entry to targets.json"; exit 1; }
link "$APP_PATH" "$HUB/app" "Angular app"
link "$CF_PATH"  "$HUB/starlabs-cloud-function" "cloud-function"
# Flutter bridge (optional) — run-flutter-test.cjs / walk-lib resolve <parent-of-hub>/breakthroughs-flutter.
# Flutter Firebase config is PER-DEV (never a committed secret): the iOS plist / Android json are generated by
# `flutterfire configure`. We verify the app targets starlabs-cicd and INSTRUCT the dev to run it if not.
if [ -n "${FLUTTER_PATH:-}" ]; then
  link "$FLUTTER_PATH" "$(dirname "$HUB")/breakthroughs-flutter" "Flutter app"
  if grep -q "starlabs-cicd" "$FLUTTER_PATH/ios/Runner/GoogleService-Info.plist" 2>/dev/null; then
    echo "✓ Flutter is configured for starlabs-cicd"
  else
    echo "⚠️  Flutter is NOT configured for starlabs-cicd — run ONCE (needs a Firebase login with access to the project):"
    echo "      (cd \"$FLUTTER_PATH\" && flutterfire configure --project=starlabs-cicd --platforms=ios,android)"
    echo "    This writes ios/Runner/GoogleService-Info.plist + android/app/google-services.json + lib/firebase_options.dart (all per-dev, gitignored)."
  fi
fi

# 2) service-account key (gitignored: *-sa.json) — admin creds for seeding; never committed
if [ -n "${STARLABS_CICD_SA:-}" ] && [ -f "$STARLABS_CICD_SA" ]; then
  cp "$STARLABS_CICD_SA" "$HUB/starlabs-cicd-sa.json"; echo "✓ SA key → $HUB/starlabs-cicd-sa.json (gitignored)"
elif [ -f "$HUB/starlabs-cicd-sa.json" ]; then
  echo "✓ SA key already present ($HUB/starlabs-cicd-sa.json)"
else
  echo "⚠️  no starlabs-cicd SA key — set STARLABS_CICD_SA=<path> (needed for the CLOUD path / some seeders; the emulator gate does not need it)"
fi

# 3) e2e node_modules (offline-friendly: reuse if present)
[ -d "$HUB/node_modules/@playwright" ] || echo "⚠️  hub node_modules missing — run: npm ci --prefix \"$HUB\" (or copy from a known-good cache)"

# 4) inject the emulator overlay (firebase.emulator.json + rules/indexes → hub; Angular env/config → app)
APP_PATH="$APP_PATH" bash "$HUB/ci/setup-emulator-config.sh"

echo "✅ setup complete. Run: APP_PATH=\"$APP_PATH\" EMU_REUSE_APP=1 bash \"$HUB/scripts/run-isolated.sh\""
