// @ts-nocheck
/**
 * seed-events.js — stand up the Events, Arena & Calendar world on the dedicated disposable test
 * project (slabs-queue-e2e-exdcz), reusing the proven queue-suite primitives (allowlist-guarded
 * admin init, the staff auth chain, the dashboard route-grant doc shape).
 *
 * Mirrors e2e/recon-allcomp/events-arena.md. PRODUCTION-SAFE BY CONSTRUCTION: every write goes
 * through seed-test-project.initAdmin() (hard-aborts off the test project), every doc is tagged
 * {testrunid:'evt', _testdata:true}, and NO ATC collection is ever touched. Events are seeded with
 * atcmodel:null so the create-event / arena ATC branches stay dead (events-arena.md "ATC exclusions").
 *
 * Actors (custom roster — events are entirely route-config-driven via the `dashboard` collection,
 * auth.guard.ts:36; there are no component-level role checks in the core CRUD paths, so the single
 * super-admin granted EVERY events role admits all 11 routes. eventopportunitydashboard exposes a
 * developer-only delete button (eod.ts:129) — the admin carries `developer` so that control renders):
 *   admin+evt@example.com         roles {admin, ah, eventcoordinator, developer, floor, mentor}
 *   participant0+evt@example.com  roles {participant}  — has an approved EPR + a deliverable
 *   participant1+evt@example.com  roles {participant}  — has an approved EPR (e-ticket issuance target)
 *   participant2+evt@example.com  roles {participant}  — has a QR scan log row (attendance-log count)
 *
 * Usage:  node e2e/events/seed-events.js --seed | --teardown
 */
'use strict';

// initAdminAuto is the SHARED emulator-aware admin init (lib/seed-common): emulator-pinned when
// FIRESTORE_EMULATOR_HOST is set, else the cloud allowlist-guarded seed.initAdmin(). One copy for all seeders.
const { seed, seedDashboardRoutes, TAG, initAdminAuto } = require('../lib/seed-common');

const TESTRUNID = process.env.EVT_RUNID || 'evt';

// ---- deterministic doc ids (run-prefixed) -------------------------------------------------------
const ID = {
  EVENT1: `${TESTRUNID}_event_1`,         // event collection (past start, future end → QR admits)
  ARENAEVT1: `${TESTRUNID}_arenaevent_1`,  // arena events (sub-event under EVENT1)
  P1: `${TESTRUNID}_P1`,                   // products (atcmodel:null)
  EPR0: `${TESTRUNID}_epr_0`,              // event participation request — approved (mark-attended target)
  EPR1: `${TESTRUNID}_epr_1`,              // event participation request — approved (e-ticket issuance target)
  D0: `${TESTRUNID}_D0`,                   // deliverable linked to EPR0 via fileref (→ completed)
  ETLOG0: `${TESTRUNID}_etlog_0`,          // arena e-ticket log row (attendance-log count oracle)
  LAYER1: `${TESTRUNID}_layer_1`,          // arenalayers row (layers-screen render)

  // --- deep-suite preconditions (events-deep.spec.ts) ---------------------------------------------
  // EVT-02 (create-event dialog writes event collection + an arena events sub-event). The arena
  // sub-event is only written when the picked product is "Installation Event Mode" AND has a
  // productToDeliverySequence whose last set carries a `delivery events` activity (update-event-
  // detail.ts:426-459). So seed an Installation product + its delivery sequence + a venue + an
  // A&H host.  The created event doc-id is generated by the dialog (collection auto-id) → asserted
  // by its run-unique NAME (no testrunid on the app write), not a known id.
  P_INST: `${TESTRUNID}_P_inst`,           // product mode "Installation Event Mode" (EVT-02 picks it)
  PTDS_INST: `${TESTRUNID}_ptds_inst`,     // productToDeliverySequence for P_INST (last set → delivery events)
  DELEVENT1: `${TESTRUNID}_delevent_1`,    // delivery events doc (the activity the arena sub-event copies)
  VENUE1: `${TESTRUNID}_venue_1`,          // event location (create-event Venue dropdown)

  // EVT-06/07/08 (QR scan). p0 carries an ACTIVE arena e-ticket for EVENT1 with producteligible=[P1]
  // so onCodeResult admits the scan and afterProductSelect writes an `arena e-ticket log/{uniqueid}`.
  ETICKET_P0: `${TESTRUNID}_eticket_p0`,   // arena e-ticket (active:true) for p0 on EVENT1
  ETLOG_DUP: `${TESTRUNID}_etlog_dup`,     // a pre-existing log row → EVT-08 duplicate-guard uniqueid

  // EVT-10/11 (initiate-event-product). A SECOND event+arena-event whose product is uninitiated for
  // 3 fresh participants (p3..p5). Their participantsproduct.status==null → they fill the table; on
  // Initiate the batch flips status→"initiated" and writes EPR status "approved". Anti-circular: we
  // seed N=3 status:null rows and assert exactly N flip to "initiated".
  EVENT2: `${TESTRUNID}_event_2`,          // event collection (the initiate event)
  ARENAEVT2: `${TESTRUNID}_arenaevent_2`,  // arena events under EVENT2 (productref → P_INST)
  PTDS_INIT: `${TESTRUNID}_ptds_init`,     // productToDeliverySequence for P_INST (initiate Delivery Set list)
  PP3: `${TESTRUNID}_pp_3`,                // participantsproduct status:null (p3) → initiated
  PP4: `${TESTRUNID}_pp_4`,                // participantsproduct status:null (p4) → initiated
  PP5: `${TESTRUNID}_pp_5`,                // participantsproduct status:null (p5) → initiated

  // EVT-13 (create-arena-space manual). A&H space-name + space-type config the manual form maps.
  SPACE1: `${TESTRUNID}_space_1`,          // A&H_Space_Name
  SPACETYPE1: `${TESTRUNID}_spacetype_1`,  // A&H_Space_Type

  // EVT-14 (videoask tag add). a videoask template + a participant submission (p0) + a tag master.
  VIDEOASK1: `${TESTRUNID}_videoask_1`,    // arenavideoask template
  PVIDEOASK0: `${TESTRUNID}_pvideoask_0`,  // participantvideoask submission (p0)
  TAG1: `${TESTRUNID}_tag_1`,              // participant tags master (tagsfor:[video ask], isActive)

  // EVT-15/16 (event-opportunity-dashboard-v2). a queue generation doc + queue_token rows (the
  // board's stage-token oracle) + the custom-stage doc id is app-generated (asserted by stagename).
  QUEUE1: `${TESTRUNID}_queue_1`,          // queue generation (selectable; queueenddate future)
  QTOK1: `${TESTRUNID}_qtok_1`,            // queue_token (Active, currentstage 'Stage A')
  QTOK2: `${TESTRUNID}_qtok_2`,            // queue_token (Active, currentstage 'Stage A')
};

const STAGE_A = 'Stage A';                 // EVT-15/16 single seeded queue stage

// Actors. profileids are run-prefixed; emails follow the actors.ts convention `<role>+<run>@example.com`.
const PF = {
  admin: `${TESTRUNID}_pf_admin`,
  p0: `${TESTRUNID}_pf_p0`,
  p1: `${TESTRUNID}_pf_p1`,
  p2: `${TESTRUNID}_pf_p2`,
  // p3..p5 are the initiate-event-product cohort (EVT-10/11): fresh participantsproduct, no EPR.
  p3: `${TESTRUNID}_pf_p3`,
  p4: `${TESTRUNID}_pf_p4`,
  p5: `${TESTRUNID}_pf_p5`,
};
const EMAIL = {
  admin: `admin+${TESTRUNID}@example.com`,
  p0: `participant0+${TESTRUNID}@example.com`,
  p1: `participant1+${TESTRUNID}@example.com`,
  p2: `participant2+${TESTRUNID}@example.com`,
  p3: `participant3+${TESTRUNID}@example.com`,
  p4: `participant4+${TESTRUNID}@example.com`,
  p5: `participant5+${TESTRUNID}@example.com`,
};

function roster() {
  const mk = (key, roles, role) => ({ uid: `${TESTRUNID}_u_${key}`, profileid: PF[key], email: EMAIL[key], role: role || key, roles });
  const staff = [
    // super-admin granted EVERY events role so the data-driven authGuard admits all 11 routes.
    mk('admin', ['admin', 'ah', 'eventcoordinator', 'developer', 'floor', 'mentor'], 'admin'),
  ];
  const participants = [
    mk('p0', ['participant'], 'participant'),
    mk('p1', ['participant'], 'participant'),
    mk('p2', ['participant'], 'participant'),
    mk('p3', ['participant'], 'participant'),
    mk('p4', ['participant'], 'participant'),
    mk('p5', ['participant'], 'participant'),
  ];
  return { staff, operators: [], participants };
}

// Routes the events specs navigate to (each needs a dashboard route-config grant).
const ROUTES = [
  { route: '/create_event', label: 'Create Event' },
  { route: '/event_participation_approve', label: 'Event Participation Approve' },
  { route: '/arena_e_ticket_approve', label: 'Arena E-Ticket Approve' },
  { route: '/qr-scanner', label: 'QR Scanner' },
  { route: '/event_attendance_log', label: 'Event Attendance Log' },
  { route: '/videoask-display', label: 'VideoAsk Display' },
  { route: '/arena_space', label: 'Arena Space' },
  { route: '/layers-screen', label: 'Layers Screen' },
  { route: '/eventopportunitydashboard', label: 'Event Opportunity Dashboard' },
  { route: '/initiateeventproduct', label: 'Initiate Event Product' },
];

async function seedEvents() {
  const admin = initAdminAuto();
  const db = admin.firestore();
  const auth = admin.auth();
  const T = admin.firestore.Timestamp;
  const tag = TAG(TESTRUNID);

  const { staff, operators, participants } = roster();

  // 1) Auth chain for the custom roster (Auth users + user_data + profile_data + users_roles + the
  //    queue DRIVEN_ROUTES grants). Reused verbatim from the queue seeder.
  await seed.seedAuthChain(db, auth, TESTRUNID, { staff, operators, participants });

  // 2) Dashboard grants for THIS group's routes.
  const staffProfileIds = staff.map((s) => s.profileid);
  const allRoles = [...new Set(staff.flatMap((s) => s.roles))];
  const participantProfileIds = participants.map((p) => p.profileid);
  await seedDashboardRoutes(db, TESTRUNID, ROUTES, { staffProfileIds, allRoles, participantProfileIds });

  // --- refs + date helpers (seed-time Node Date — same machine/TZ as the test browser) ---
  const profileRef = (pf) => db.collection('profile_data').doc(pf);
  const productRef = (id) => db.collection('products').doc(id);
  const eventRef = db.collection('event collection').doc(ID.EVENT1);
  const eprRef = (id) => db.collection('event participation request').doc(id);
  const daysFromNow = (d) => T.fromMillis(Date.now() + d * 86400e3);

  // 3) PRODUCT (atcmodel:null so the ATC branches in create-event/initiate stay dead). The approve +
  //    e-ticket screens render `mapProduct[productref.id]` / `mapProducts[productref.id].product`, so
  //    the doc must exist with a `product` field; keyed by both `id` and the doc id (getProductMap maps
  //    by doc id, arena-e-ticket-approve maps by data['id']).
  await productRef(ID.P1).set({ id: ID.P1, docid: ID.P1, product: `TEST Event Product ${TESTRUNID}`, atcmodel: null, ...tag });

  // 4) EVENT — start in the PAST, end in the FUTURE (qr-scanner.ts:82 only admits events whose
  //    end_date >= now; event-list renders name/venue and calls start_date/end_date .toDate()).
  await eventRef.set({
    docid: ID.EVENT1, event_id: ID.EVENT1, name: `TEST Event ${TESTRUNID}`,
    venue: `TEST Venue ${TESTRUNID}`, address: 'Test Address',
    start_date: daysFromNow(-2), end_date: daysFromNow(7),
    hosts: [], atcmodel: null, notifyparticipants: false, addtocalendar: false,
    ...tag,
  });

  // 5) ARENA EVENT — sub-event under EVENT1 (initiateeventproduct reads productref/eventref/docid).
  await db.collection('arena events').doc(ID.ARENAEVT1).set({
    docid: ID.ARENAEVT1, title: `TEST Arena Event ${TESTRUNID}`,
    productref: productRef(ID.P1), eventref: eventRef,
    startdate: daysFromNow(-2), enddate: daysFromNow(7), heroevent: false, delete: false,
    ...tag,
  });

  // 6) EVENT PARTICIPATION REQUESTS — both status "approved" so they surface in the approve screen's
  //    "Mark Attendence" tab (status in [approved,unattended]) AND the e-ticket screen's
  //    (eventref==X && status==approved) query. profileid == the seeded profile_data doc id (the row's
  //    client name is mapProfileName[profileid]); productref → the seeded product (row's product cell);
  //    eventref → the event; arenaeventid set for the initiate flow.
  const mkEpr = (id, pf) => ({
    docid: id, profileid: PF[pf], eventref: eventRef, productref: productRef(ID.P1),
    arenaeventid: ID.ARENAEVT1, participantproductid: null, status: 'approved',
    initiatedfrom: 'web', ...tag,
  });
  await eprRef(ID.EPR0).set(mkEpr(ID.EPR0, 'p0'));
  await eprRef(ID.EPR1).set(mkEpr(ID.EPR1, 'p1'));

  // 7) DELIVERABLE linked to EPR0 via fileref (markAsAttended queries deliverables where fileref
  //    array-contains-any [EPRref] and flips status→"completed"). Starts "ongoing" — a PRECONDITION;
  //    the spec asserts the "completed" the APP writes, never this seeded value.
  await db.collection('deliverables').doc(ID.D0).set({
    docid: ID.D0, profileid: PF.p0, type: 'event', status: 'ongoing',
    fileref: [eprRef(ID.EPR0)], ...tag,
  });

  // 8) ARENA E-TICKET LOG row for the attendance-log count oracle (EVT-09). event-attendance-log
  //    streams `arena e-ticket log` where eventref==X and renders Unique-Participant count from the
  //    distinct profileids. One seeded row → the board computes 1; countWhere agrees independently.
  await db.collection('arena e-ticket log').doc(ID.ETLOG0).set({
    docid: ID.ETLOG0, profileid: PF.p2, eventref: eventRef,
    product: productRef(ID.P1), logdate: T.now(),
    eticketref: db.collection('arena e-ticket').doc(`${TESTRUNID}_eticket_ph`), ...tag,
  });

  // 9) ARENALAYERS row for the layers-screen render (EVT-12). layers-screen streams arenalayers where
  //    eventref==X and renders rows ordered by sequence; the row's title is asserted in the table.
  await db.collection('arenalayers').doc(ID.LAYER1).set({
    docid: ID.LAYER1, title: `TEST Layer ${TESTRUNID}`,
    description: ['Layer detail one', 'Layer detail two'],
    sequence: 1, eventref: eventRef, delete: false, ...tag,
  });

  // =================================================================================================
  // DEEP-SUITE PRECONDITIONS (events-deep.spec.ts — EVT-02/06/07/08/10/11/13/14/15/16)
  // =================================================================================================

  const event2Ref = db.collection('event collection').doc(ID.EVENT2);

  // 10) EVT-02: the create-event dialog only writes an `arena events` sub-event when the picked
  //     product is "Installation Event Mode" AND has a productToDeliverySequence whose LAST set's
  //     deliverysequence contains a `delivery events` activity (update-event-detail.ts:428-459).
  //     Seed that product + sequence + the delivery-events doc it references.
  await productRef(ID.P_INST).set({
    id: ID.P_INST, docid: ID.P_INST, product: `TEST Install Product ${TESTRUNID}`,
    mode: 'Installation Event Mode', atcmodel: null, ...tag,
  });
  await db.collection('delivery events').doc(ID.DELEVENT1).set({
    docid: ID.DELEVENT1, eventname: `TEST Delivery Event ${TESTRUNID}`, ...tag,
  });
  // productToDeliverySequence.product → the product ref; deliveryoptions[last].deliverysequence has an
  // activity whose path starts "delivery events" so the create-event save resolves findeventactivity.
  const mkPtds = (id, productId) => ({
    docid: id, product: productRef(productId),
    deliveryoptions: [{
      deliverytype: `TEST Delivery Set ${TESTRUNID}`,
      deliverysequence: [{ activity: db.collection('delivery events').doc(ID.DELEVENT1) }],
    }],
    ...tag,
  });
  await db.collection('productToDeliverySequence').doc(ID.PTDS_INST).set(mkPtds(ID.PTDS_INST, ID.P_INST));
  // event location → the create-event Venue dropdown (collectionData orderBy 'location').
  await db.collection('event location').doc(ID.VENUE1).set({
    docid: ID.VENUE1, location: `TEST Location ${TESTRUNID}`, ...tag,
  });
  // The admin must be an A&H member so it appears in the create-event Hosts dropdown
  // (update-event-detail.ts:278 users_roles where ahmember==true). seedAuthChain wrote the role doc
  // keyed by a run-id; flip ahmember:true + give it a stable display name + profile_ref.
  const adminRoleId = `${TESTRUNID}_role_admin`;
  await db.collection('users_roles').doc(adminRoleId).set({
    ahmember: true, name: `TEST Host ${TESTRUNID}`, profile_ref: profileRef(PF.admin), ...tag,
  }, { merge: true });

  // 11) EVT-06/07/08 (QR scan): an ACTIVE arena e-ticket for p0 on EVENT1 with producteligible=[P1].
  //     onCodeResult admits (active===true + within EVENT1 date window) → product chip → afterProductSelect
  //     writes `arena e-ticket log/{uniqueid}`. EVT-06 flips active→false in the e-ticket screen first.
  await db.collection('arena e-ticket').doc(ID.ETICKET_P0).set({
    docid: ID.ETICKET_P0, profileid: PF.p0, eventref: eventRef,
    eventparticipationref: eprRef(ID.EPR0), producteligible: [ID.P1], active: true,
    eventstartdate: daysFromNow(-2), eventenddate: daysFromNow(7), ...tag,
  });
  // EVT-08 duplicate guard: a log row already keyed by a known uniqueid → a re-scan of that uniqueid
  // hits maplog[uniqueid] and sets usedticket (no second write). docid == uniqueid (the dedup key).
  await db.collection('arena e-ticket log').doc(ID.ETLOG_DUP).set({
    docid: ID.ETLOG_DUP, profileid: PF.p0, eventref: eventRef,
    product: productRef(ID.P1), logdate: T.now(),
    eticketref: db.collection('arena e-ticket').doc(ID.ETICKET_P0), ...tag,
  });

  // 12) EVT-10/11 (initiate-event-product): a SECOND event + arena-event (productref → P_INST), and 3
  //     fresh participantsproduct (status:null) for p3..p5 with NO EPR — so onArenaEventSelect lists
  //     them as eligible-to-initiate rows. On Initiate the batch flips status→"initiated".
  await event2Ref.set({
    docid: ID.EVENT2, event_id: ID.EVENT2, name: `TEST Initiate Event ${TESTRUNID}`,
    venue: `TEST Venue ${TESTRUNID}`, address: 'Test Address',
    start_date: daysFromNow(-1), end_date: daysFromNow(14),
    hosts: [], atcmodel: null, notifyparticipants: false, addtocalendar: false,
    arenaeventidlist: [ID.ARENAEVT2], ...tag,
  });
  await db.collection('arena events').doc(ID.ARENAEVT2).set({
    docid: ID.ARENAEVT2, title: `TEST Initiate Arena ${TESTRUNID}`, eventname: `TEST Initiate Event ${TESTRUNID}`,
    productref: productRef(ID.P_INST), eventref: event2Ref, type: 'event',
    startdate: daysFromNow(-1), enddate: daysFromNow(14), heroevent: false, delete: false, ...tag,
  });
  // initiate reads productToDeliverySequence where product==arena.productref (limit 1) → the Delivery Set
  // dropdown. Reuse the P_INST sequence shape (a separate doc id, same product ref).
  await db.collection('productToDeliverySequence').doc(ID.PTDS_INIT).set(mkPtds(ID.PTDS_INIT, ID.P_INST));
  // Fresh uninitiated participantsproduct rows (status:null) for p3..p5. productref → P_INST so
  // onArenaEventSelect's (productref==X && status==null) query lists them.
  const mkPP = (id, pf) => ({
    docid: id, profileid: PF[pf], productref: productRef(ID.P_INST), status: null,
    name: EMAIL[pf], email: EMAIL[pf], ...tag,
  });
  await db.collection('participantsproduct').doc(ID.PP3).set(mkPP(ID.PP3, 'p3'));
  await db.collection('participantsproduct').doc(ID.PP4).set(mkPP(ID.PP4, 'p4'));
  await db.collection('participantsproduct').doc(ID.PP5).set(mkPP(ID.PP5, 'p5'));

  // 13) EVT-13 (create-arena-space manual): A&H space-name + space-type the manual form dropdowns map.
  await db.collection('A&H_Space_Name').doc(ID.SPACE1).set({
    docid: ID.SPACE1, spacename: `TEST Space ${TESTRUNID}`, ...tag,
  });
  await db.collection('A&H_Space_Type').doc(ID.SPACETYPE1).set({
    docid: ID.SPACETYPE1, typename: `TEST Engagement ${TESTRUNID}`, ...tag,
  });

  // 14) EVT-14 (videoask tag add): a videoask template + a participant submission (p0) + a tag master.
  //     The tag column renders one checkbox per `participant tags` where tagsfor array-contains 'video
  //     ask' AND isActive==true; the checkbox uses tag.id + tag.name. On click → updateDoc adds the tag
  //     id to participantvideoask.tags and writes a `participant tag logs` row.
  await db.collection('arenavideoask').doc(ID.VIDEOASK1).set({
    docid: ID.VIDEOASK1, title: `TEST VideoAsk ${TESTRUNID}`, eventref: eventRef, ...tag,
  });
  await db.collection('participantvideoask').doc(ID.PVIDEOASK0).set({
    docid: ID.PVIDEOASK0, profileid: PF.p0, videoaskid: ID.VIDEOASK1, arenaevent: eventRef,
    fileurl: null, uploaded: T.now(), tags: [], ...tag,
  });
  await db.collection('participant tags').doc(ID.TAG1).set({
    docid: ID.TAG1, id: ID.TAG1, name: `TEST Tag ${TESTRUNID}`,
    tagsfor: ['video ask'], isActive: true, ...tag,
  });

  // 15) EVT-15/16 (event-opportunity-dashboard-v2): a selectable queue + queue_token rows.
  //     queue generation must have a future queueenddate (board filter), a `stages` array, and a
  //     `stageproperty` map. With empty compulsoryactivity, fetchdata() emits one stage entry
  //     {queueid, stagename, status:null} → the EVT-15 stage dropdown; status:null means the EVT-16
  //     board count is the FULL active-token tokenlist for the stage (no status filter).
  const queueRef = db.collection('queue generation').doc(ID.QUEUE1);
  await queueRef.set({
    docid: ID.QUEUE1, queuename: `TEST EOD Queue ${TESTRUNID}`,
    queueenddate: daysFromNow(30), delete: false,
    stages: [STAGE_A], stageproperty: { [STAGE_A]: { compulsoryactivity: {} } },
    ...tag,
  });
  // Active queue_token rows the child EventOpportunityComponent groups by currentstage into the
  // stageTokenMap (component ts:344-372). EVT-16 oracle = count of these (queueref + tokenstatus +
  // currentstage). tokenstatus MUST be exactly "Active" (the child's where filter is case-sensitive).
  const mkTok = (id, pf) => ({
    docid: id, profile_id: PF[pf], profileid: PF[pf], profile_name: EMAIL[pf],
    queueref: queueRef, currentstage: STAGE_A, tokenstatus: 'Active', status: 'queued',
    logdate: T.now(), ...tag,
  });
  await db.collection('queue_token').doc(ID.QTOK1).set(mkTok(ID.QTOK1, 'p3'));
  await db.collection('queue_token').doc(ID.QTOK2).set(mkTok(ID.QTOK2, 'p4'));

  // 16) ENVIRONMENT HYGIENE: several event-group screens (qr-scanner, videoask-display, eod-v2) do a
  //     FULL `event collection` scan and eagerly call doc['end_date'].toDate() / start_date.toDate()
  //     on EVERY doc (e.g. qr-scanner.ts:82). A foreign doc from another suite's seed (e.g. the queue
  //     suite's `run1_bigevt_0`, which carries `startdate/enddate` but NOT the underscored
  //     `start_date/end_date`) makes that loop THROW, crashing the screen before it renders. We don't
  //     own that doc, so defensively BACKFILL the underscored dates on any event collection doc missing
  //     them (idempotent; only fills the missing fields). This is shared-project hygiene so the events
  //     screens mount cleanly — it does not touch the queue suite's own fields. NOT an asserted value.
  const allEvents = await db.collection('event collection').get();
  for (const ev of allEvents.docs) {
    const data = ev.data();
    const patch = {};
    if (data['start_date'] == null) patch['start_date'] = data['startdate'] ?? daysFromNow(-30);
    if (data['end_date'] == null) patch['end_date'] = data['enddate'] ?? daysFromNow(-1);
    if (Object.keys(patch).length) await ev.ref.set(patch, { merge: true });
  }

  return {
    TESTRUNID, ID, PF, EMAIL,
    counts: {
      events: 2, arenaEvents: 2, epr: 2, deliverables: 1, eticketLog: 2, layers: 1,
      products: 2, ptds: 2, eticket: 1, participantsproduct: 3, spaces: 1, spacetypes: 1,
      videoask: 1, participantvideoask: 1, tags: 1, queues: 1, queueTokens: 2, venues: 1,
    },
  };
}

// Collections this seed writes (for teardown). Spaced names are Firestore strings — pass verbatim.
const SEEDED = [
  'products', 'event collection', 'arena events', 'event participation request',
  'deliverables', 'arena e-ticket log', 'arenalayers',
  // deep-suite precondition collections
  'productToDeliverySequence', 'delivery events', 'event location',
  'participantsproduct', 'A&H_Space_Name', 'A&H_Space_Type',
  'arenavideoask', 'participantvideoask', 'participant tags', 'queue generation', 'queue_token',
  // mutation-test outputs (so re-runs start clean): markAsAttended creates events_profiles; the e-ticket
  // issuance test creates `arena e-ticket`; videoask tagging creates `participant tag logs` / updates
  // `participant metadata`; create-arena-space creates `arenaspace`; the EOD form creates
  // `stage opportunity count`. The APP writes some of these with NO testrunid → the spec resets/cleans
  // them by natural key (see support/events.ts); teardown still sweeps the testrunid-tagged ones.
  'events_profiles', 'arena e-ticket', 'arenaspace', 'stage opportunity count',
  'participant tag logs', 'participant metadata',
  // auth-chain + dashboard (shared shape; testrunid-scoped so the queue 'run1' seed is untouched)
  'user_data', 'profile_data', 'users_roles', 'dashboard',
];

async function teardownEvents() {
  const admin = initAdminAuto();
  const db = admin.firestore();
  const n = await seed.teardownCollections(db, SEEDED, TESTRUNID);
  // Also delete the Auth users (uids carry the run id).
  const auth = admin.auth();
  for (const key of Object.keys(PF)) {
    await auth.deleteUser(`${TESTRUNID}_u_${key}`).catch(() => {});
  }
  return n;
}

module.exports = { TESTRUNID, ID, PF, EMAIL, ROUTES, SEEDED, seedEvents, teardownEvents };

if (require.main === module) {
  const mode = process.argv[2];
  (async () => {
    if (mode === '--seed') { const r = await seedEvents(); console.log('[seed-events] seeded', JSON.stringify(r.counts), 'run=', r.TESTRUNID); }
    else if (mode === '--teardown') { const n = await teardownEvents(); console.log('[seed-events] torn down', n, 'docs for run', TESTRUNID); }
    else { console.log('usage: seed-events.js --seed | --teardown'); process.exit(1); }
    process.exit(0);
  })().catch((e) => { console.error('FAILED:', e.message || e); process.exit(1); });
}
