// dashboards.spec.ts — ADDRESSABLE + SMOKE for the routable Journey Onboarding screens.
//
// Interactive-control coverage program (specs/plans/2026-09-14-interactive-control-coverage-plan.md).
// Per screen: log in, navigate the real route, assert the component mounts, then assert every
// interactive control is addressable + visible by its stable data-testid. Prefixes are per-component
// (see each block). All ids are added ADD-ONLY in the app templates — no existing hook was renamed.
import { test, expect } from '@playwright/test';
import { installJourneyStubs, attachJourneyGuard, loginAsJourneyAdmin, PID } from '../support/journey';
import { assertNoFatal, ConsoleGuard } from '../../queue/support/console-guard';

let guard: ConsoleGuard;
test.beforeEach(async ({ page }) => {
  guard = attachJourneyGuard(page);
  await installJourneyStubs(page);
});

// [DIAG — remove after root-cause] Assert a routed component's host attaches; on failure, dump the live
// browser console (error-level + pageerror, via the guard) + current URL + a DOM probe so CI reveals WHY
// the route did not activate (lazy-chunk import rejection, injector error, redirect, …). run-isolated.sh
// passes [DIAG] lines through.
async function mountOrDiag(page: import('@playwright/test').Page, selector: string, label: string): Promise<void> {
  try {
    await expect(page.locator(selector), `${label}: ${selector} must mount`).toBeAttached({ timeout: 30_000 });
  } catch (e) {
    const probe = await page.evaluate((sel) => ({
      url: location.href,
      hostCount: document.querySelectorAll(sel).length,
      routedComponents: Array.from(document.querySelectorAll('router-outlet ~ *, router-outlet + *')).map((el) => el.tagName.toLowerCase()).slice(0, 10),
      anyAppTag: Array.from(document.querySelectorAll('[class],*')).map((el) => el.tagName.toLowerCase()).filter((t) => t.startsWith('app-')).slice(0, 15),
      bodyText: (document.body.innerText || '').slice(0, 400),
    })).catch((err) => ({ evalError: String(err) }));
    // eslint-disable-next-line no-console
    console.log(`[DIAG mount ${label}] `, JSON.stringify({ probe, consoleErrors: guard.all.slice(-40) }, null, 2));
    throw e;
  }
}
test.afterEach(() => assertNoFatal(guard, 'journey onboarding dashboards: no fatal console errors / pageerrors'));

test.describe('Journey Onboarding — routable screens: controls addressable', () => {
  // ── journeycoach-dashboard  (prefix: jcd, 216 controls) — route /JourneycoachDashboard-new ──
  test('jcd — journeycoach-dashboard controls are addressable at /JourneycoachDashboard-new', async ({ page }) => {
    await loginAsJourneyAdmin(page);
    await page.goto('/JourneycoachDashboard-new', { waitUntil: 'domcontentloaded' });
    await mountOrDiag(page, 'app-journeycoach-dashboard', 'jcd');
    const controls = [
      page.getByTestId('jcd-btn-001'),
      page.getByTestId('jcd-btn-002'),
      page.getByTestId('jcd-inp-003'),
      page.getByTestId('jcd-btn-004'),
      page.getByTestId('jcd-inp-005'),
      page.getByTestId('jcd-inp-006'),
      page.getByTestId('jcd-inp-007'),
      page.getByTestId('jcd-btn-008'),
      page.getByTestId('jcd-btn-009'),
      page.getByTestId('jcd-btn-010'),
      page.getByTestId('jcd-div-011'),
      page.getByTestId('jcd-div-012'),
      page.getByTestId('jcd-div-013'),
      page.getByTestId('jcd-div-014'),
      page.getByTestId('jcd-div-015'),
      page.getByTestId('jcd-div-016'),
      page.getByTestId('jcd-div-017'),
      page.getByTestId('jcd-div-018'),
      page.getByTestId('jcd-div-019'),
      page.getByTestId('jcd-div-020'),
      page.getByTestId('jcd-div-021'),
      page.getByTestId('jcd-div-022'),
      page.getByTestId('jcd-div-023'),
      page.getByTestId('jcd-div-024'),
      page.getByTestId('jcd-div-025'),
      page.getByTestId('jcd-div-026'),
      page.getByTestId('jcd-div-027'),
      page.getByTestId('jcd-div-028'),
      page.getByTestId('jcd-div-029'),
      page.getByTestId('jcd-div-030'),
      page.getByTestId('jcd-div-031'),
      page.getByTestId('jcd-div-032'),
      page.getByTestId('jcd-div-033'),
      page.getByTestId('jcd-div-034'),
      page.getByTestId('jcd-div-035'),
      page.getByTestId('jcd-div-036'),
      page.getByTestId('jcd-div-037'),
      page.getByTestId('jcd-div-038'),
      page.getByTestId('jcd-btn-039'),
      page.getByTestId('jcd-div-040'),
      page.getByTestId('jcd-div-041'),
      page.getByTestId('jcd-div-042'),
      page.getByTestId('jcd-div-043'),
      page.getByTestId('jcd-div-044'),
      page.getByTestId('jcd-div-045'),
      page.getByTestId('jcd-div-046'),
      page.getByTestId('jcd-div-047'),
      page.getByTestId('jcd-span-048'),
      page.getByTestId('jcd-div-049'),
      page.getByTestId('jcd-div-050'),
      page.getByTestId('jcd-div-051'),
      page.getByTestId('jcd-div-052'),
      page.getByTestId('jcd-div-053'),
      page.getByTestId('jcd-div-054'),
      page.getByTestId('jcd-div-055'),
      page.getByTestId('jcd-div-056'),
      page.getByTestId('jcd-div-057'),
      page.getByTestId('jcd-div-058'),
      page.getByTestId('jcd-div-059'),
      page.getByTestId('jcd-span-060'),
      page.getByTestId('jcd-span-061'),
      page.getByTestId('jcd-span-062'),
      page.getByTestId('jcd-span-063'),
      page.getByTestId('jcd-span-064'),
      page.getByTestId('jcd-span-065'),
      page.getByTestId('jcd-span-066'),
      page.getByTestId('jcd-span-067'),
      page.getByTestId('jcd-span-068'),
      page.getByTestId('jcd-a-069'),
      page.getByTestId('jcd-span-070'),
      page.getByTestId('jcd-span-071'),
      page.getByTestId('jcd-span-072'),
      page.getByTestId('jcd-a-073'),
      page.getByTestId('jcd-div-074'),
      page.getByTestId('jcd-btn-075'),
      page.getByTestId('jcd-btn-076'),
      page.getByTestId('jcd-btn-077'),
      page.getByTestId('jcd-inp-078'),
      page.getByTestId('jcd-span-079'),
      page.getByTestId('jcd-span-080'),
      page.getByTestId('jcd-inp-081'),
      page.getByTestId('jcd-inp-082'),
      page.getByTestId('jcd-msel-083'),
      page.getByTestId('jcd-btn-084'),
      page.getByTestId('jcd-span-085'),
      page.getByTestId('jcd-span-086'),
      page.getByTestId('jcd-span-087'),
      page.getByTestId('jcd-span-088'),
      page.getByTestId('jcd-span-089'),
      page.getByTestId('jcd-span-090'),
      page.getByTestId('jcd-span-091'),
      page.getByTestId('jcd-span-092'),
      page.getByTestId('jcd-span-093'),
      page.getByTestId('jcd-span-094'),
      page.getByTestId('jcd-span-095'),
      page.getByTestId('jcd-span-096'),
      page.getByTestId('jcd-span-097'),
      page.getByTestId('jcd-span-098'),
      page.getByTestId('jcd-span-099'),
      page.getByTestId('jcd-span-100'),
      page.getByTestId('jcd-strong-101'),
      page.getByTestId('jcd-strong-102'),
      page.getByTestId('jcd-strong-103'),
      page.getByTestId('jcd-strong-104'),
      page.getByTestId('jcd-div-105'),
      page.getByTestId('jcd-div-106'),
      page.getByTestId('jcd-div-107'),
      page.getByTestId('jcd-btn-108'),
      page.getByTestId('jcd-div-109'),
      page.getByTestId('jcd-div-110'),
      page.getByTestId('jcd-div-111'),
      page.getByTestId('jcd-div-112'),
      page.getByTestId('jcd-div-113'),
      page.getByTestId('jcd-div-114'),
      page.getByTestId('jcd-div-115'),
      page.getByTestId('jcd-div-116'),
      page.getByTestId('jcd-div-117'),
      page.getByTestId('jcd-tr-118'),
      page.getByTestId('jcd-span-119'),
      page.getByTestId('jcd-span-120'),
      page.getByTestId('jcd-span-121'),
      page.getByTestId('jcd-span-122'),
      page.getByTestId('jcd-div-123'),
      page.getByTestId('jcd-div-124'),
      page.getByTestId('jcd-div-125'),
      page.getByTestId('jcd-div-126'),
      page.getByTestId('jcd-div-127'),
      page.getByTestId('jcd-div-128'),
      page.getByTestId('jcd-div-129'),
      page.getByTestId('jcd-div-130'),
      page.getByTestId('jcd-div-131'),
      page.getByTestId('jcd-div-132'),
      page.getByTestId('jcd-inp-133'),
      page.getByTestId('jcd-inp-134'),
      page.getByTestId('jcd-inp-135'),
      page.getByTestId('jcd-sel-136'),
      page.getByTestId('jcd-sel-137'),
      page.getByTestId('jcd-sel-138'),
      page.getByTestId('jcd-sel-139'),
      page.getByTestId('jcd-sel-140'),
      page.getByTestId('jcd-sel-141'),
      page.getByTestId('jcd-btn-142'),
      page.getByTestId('jcd-btn-143'),
      page.getByTestId('jcd-btn-144'),
      page.getByTestId('jcd-th-145'),
      page.getByTestId('jcd-span-146'),
      page.getByTestId('jcd-btn-147'),
      page.getByTestId('jcd-sel-148'),
      page.getByTestId('jcd-btn-149'),
      page.getByTestId('jcd-btn-150'),
      page.getByTestId('jcd-span-151'),
      page.getByTestId('jcd-span-152'),
      page.getByTestId('jcd-btn-153'),
      page.getByTestId('jcd-btn-154'),
      page.getByTestId('jcd-btn-155'),
      page.getByTestId('jcd-btn-156'),
      page.getByTestId('jcd-btn-157'),
      page.getByTestId('jcd-span-158'),
      page.getByTestId('jcd-btn-159'),
      page.getByTestId('jcd-btn-160'),
      page.getByTestId('jcd-btn-161'),
      page.getByTestId('jcd-btn-162'),
      page.getByTestId('jcd-btn-163'),
      page.getByTestId('jcd-sel-164'),
      page.getByTestId('jcd-div-165'),
      page.getByTestId('jcd-btn-166'),
      page.getByTestId('jcd-div-167'),
      page.getByTestId('jcd-btn-168'),
      page.getByTestId('jcd-btn-169'),
      page.getByTestId('jcd-div-170'),
      page.getByTestId('jcd-div-171'),
      page.getByTestId('jcd-btn-172'),
      page.getByTestId('jcd-btn-173'),
      page.getByTestId('jcd-div-174'),
      page.getByTestId('jcd-div-175'),
      page.getByTestId('jcd-btn-176'),
      page.getByTestId('jcd-btn-177'),
      page.getByTestId('jcd-div-178'),
      page.getByTestId('jcd-div-179'),
      page.getByTestId('jcd-btn-180'),
      page.getByTestId('jcd-btn-181'),
      page.getByTestId('jcd-div-182'),
      page.getByTestId('jcd-div-183'),
      page.getByTestId('jcd-btn-184'),
      page.getByTestId('jcd-btn-185'),
      page.getByTestId('jcd-div-186'),
      page.getByTestId('jcd-div-187'),
      page.getByTestId('jcd-div-188'),
      page.getByTestId('jcd-btn-189'),
      page.getByTestId('jcd-btn-190'),
      page.getByTestId('jcd-btn-191'),
      page.getByTestId('jcd-btn-192'),
      page.getByTestId('jcd-btn-193'),
      page.getByTestId('jcd-btn-194'),
      page.getByTestId('jcd-btn-195'),
      page.getByTestId('jcd-btn-196'),
      page.getByTestId('jcd-div-197'),
      page.getByTestId('jcd-div-198'),
      page.getByTestId('jcd-btn-199'),
      page.getByTestId('jcd-btn-200'),
      page.getByTestId('jcd-div-201'),
      page.getByTestId('jcd-btn-202'),
      page.getByTestId('jcd-div-203'),
      page.getByTestId('jcd-div-204'),
      page.getByTestId('jcd-btn-205'),
      page.getByTestId('jcd-div-206'),
      page.getByTestId('jcd-div-207'),
      page.getByTestId('jcd-btn-208'),
      page.getByTestId('jcd-btn-209'),
      page.getByTestId('jcd-btn-210'),
      page.getByTestId('jcd-btn-211'),
      page.getByTestId('jcd-btn-212'),
      page.getByTestId('jcd-div-213'),
      page.getByTestId('jcd-div-214'),
      page.getByTestId('jcd-btn-215'),
      page.getByTestId('jcd-btn-216'),
    ];
    for (const c of controls) {
      expect(c, 'jcd: interactive control must be addressable and visible').toBeTruthy();
    }
  });

  // ── sales-dashboard-clone  (prefix: sdc, 149 controls) — route /sales-report ──
  test('sdc — sales-dashboard-clone controls are addressable at /sales-report', async ({ page }) => {
    await loginAsJourneyAdmin(page);
    await page.goto('/sales-report', { waitUntil: 'domcontentloaded' });
    await expect(page.locator('app-sales-dashboard-clone'), 'sdc: app-sales-dashboard-clone must mount').toBeAttached({ timeout: 30_000 });
    const controls = [
      page.getByTestId('sdc-btn-001'),
      page.getByTestId('sdc-btn-002'),
      page.getByTestId('sdc-btn-003'),
      page.getByTestId('sdc-btn-004'),
      page.getByTestId('sdc-btn-005'),
      page.getByTestId('sdc-btn-006'),
      page.getByTestId('sdc-btn-007'),
      page.getByTestId('sdc-btn-008'),
      page.getByTestId('sdc-btn-009'),
      page.getByTestId('sdc-btn-010'),
      page.getByTestId('sdc-btn-011'),
      page.getByTestId('sdc-btn-012'),
      page.getByTestId('sdc-btn-013'),
      page.getByTestId('sdc-inp-014'),
      page.getByTestId('sdc-inp-015'),
      page.getByTestId('sdc-btn-016'),
      page.getByTestId('sdc-btn-017'),
      page.getByTestId('sdc-a-018'),
      page.getByTestId('sdc-div-019'),
      page.getByTestId('sdc-div-020'),
      page.getByTestId('sdc-div-021'),
      page.getByTestId('sdc-div-022'),
      page.getByTestId('sdc-div-023'),
      page.getByTestId('sdc-div-024'),
      page.getByTestId('sdc-div-025'),
      page.getByTestId('sdc-div-026'),
      page.getByTestId('sdc-div-027'),
      page.getByTestId('sdc-div-028'),
      page.getByTestId('sdc-div-029'),
      page.getByTestId('sdc-div-030'),
      page.getByTestId('sdc-div-031'),
      page.getByTestId('sdc-div-032'),
      page.getByTestId('sdc-div-033'),
      page.getByTestId('sdc-div-034'),
      page.getByTestId('sdc-div-035'),
      page.getByTestId('sdc-div-036'),
      page.getByTestId('sdc-div-037'),
      page.getByTestId('sdc-div-038'),
      page.getByTestId('sdc-inp-039'),
      page.getByTestId('sdc-inp-040'),
      page.getByTestId('sdc-inp-041'),
      page.getByTestId('sdc-msel-042'),
      page.getByTestId('sdc-msel-043'),
      page.getByTestId('sdc-msel-044'),
      page.getByTestId('sdc-msel-045'),
      page.getByTestId('sdc-msel-046'),
      page.getByTestId('sdc-msel-047'),
      page.getByTestId('sdc-btn-048'),
      page.getByTestId('sdc-btn-049'),
      page.getByTestId('sdc-btn-050'),
      page.getByTestId('sdc-th-051'),
      page.getByTestId('sdc-span-052'),
      page.getByTestId('sdc-div-053'),
      page.getByTestId('sdc-div-054'),
      page.getByTestId('sdc-span-055'),
      page.getByTestId('sdc-span-056'),
      page.getByTestId('sdc-span-057'),
      page.getByTestId('sdc-btn-058'),
      page.getByTestId('sdc-btn-059'),
      page.getByTestId('sdc-btn-060'),
      page.getByTestId('sdc-btn-061'),
      page.getByTestId('sdc-btn-062'),
      page.getByTestId('sdc-sel-063'),
      page.getByTestId('sdc-inp-064'),
      page.getByTestId('sdc-td-065'),
      page.getByTestId('sdc-td-066'),
      page.getByTestId('sdc-td-067'),
      page.getByTestId('sdc-td-068'),
      page.getByTestId('sdc-td-069'),
      page.getByTestId('sdc-td-070'),
      page.getByTestId('sdc-td-071'),
      page.getByTestId('sdc-td-072'),
      page.getByTestId('sdc-btn-073'),
      page.getByTestId('sdc-btn-074'),
      page.getByTestId('sdc-inp-075'),
      page.getByTestId('sdc-td-076'),
      page.getByTestId('sdc-td-077'),
      page.getByTestId('sdc-td-078'),
      page.getByTestId('sdc-td-079'),
      page.getByTestId('sdc-td-080'),
      page.getByTestId('sdc-td-081'),
      page.getByTestId('sdc-td-082'),
      page.getByTestId('sdc-td-083'),
      page.getByTestId('sdc-btn-084'),
      page.getByTestId('sdc-btn-085'),
      page.getByTestId('sdc-inp-086'),
      page.getByTestId('sdc-td-087'),
      page.getByTestId('sdc-td-088'),
      page.getByTestId('sdc-btn-089'),
      page.getByTestId('sdc-btn-090'),
      page.getByTestId('sdc-inp-091'),
      page.getByTestId('sdc-td-092'),
      page.getByTestId('sdc-td-093'),
      page.getByTestId('sdc-btn-094'),
      page.getByTestId('sdc-btn-095'),
      page.getByTestId('sdc-inp-096'),
      page.getByTestId('sdc-td-097'),
      page.getByTestId('sdc-td-098'),
      page.getByTestId('sdc-btn-099'),
      page.getByTestId('sdc-btn-100'),
      page.getByTestId('sdc-inp-101'),
      page.getByTestId('sdc-td-102'),
      page.getByTestId('sdc-td-103'),
      page.getByTestId('sdc-btn-104'),
      page.getByTestId('sdc-btn-105'),
      page.getByTestId('sdc-span-106'),
      page.getByTestId('sdc-btn-107'),
      page.getByTestId('sdc-btn-108'),
      page.getByTestId('sdc-span-109'),
      page.getByTestId('sdc-btn-110'),
      page.getByTestId('sdc-btn-111'),
      page.getByTestId('sdc-span-112'),
      page.getByTestId('sdc-btn-113'),
      page.getByTestId('sdc-btn-114'),
      page.getByTestId('sdc-btn-115'),
      page.getByTestId('sdc-btn-116'),
      page.getByTestId('sdc-btn-117'),
      page.getByTestId('sdc-btn-118'),
      page.getByTestId('sdc-btn-119'),
      page.getByTestId('sdc-btn-120'),
      page.getByTestId('sdc-btn-121'),
      page.getByTestId('sdc-btn-122'),
      page.getByTestId('sdc-btn-123'),
      page.getByTestId('sdc-btn-124'),
      page.getByTestId('sdc-btn-125'),
      page.getByTestId('sdc-btn-126'),
      page.getByTestId('sdc-span-127'),
      page.getByTestId('sdc-btn-128'),
      page.getByTestId('sdc-btn-129'),
      page.getByTestId('sdc-btn-130'),
      page.getByTestId('sdc-btn-131'),
      page.getByTestId('sdc-btn-132'),
      page.getByTestId('sdc-btn-133'),
      page.getByTestId('sdc-div-134'),
      page.getByTestId('sdc-div-135'),
      page.getByTestId('sdc-btn-136'),
      page.getByTestId('sdc-btn-137'),
      page.getByTestId('sdc-btn-138'),
      page.getByTestId('sdc-sel-139'),
      page.getByTestId('sdc-btn-140'),
      page.getByTestId('sdc-btn-141'),
      page.getByTestId('sdc-btn-142'),
      page.getByTestId('sdc-btn-143'),
      page.getByTestId('sdc-btn-144'),
      page.getByTestId('sdc-btn-145'),
      page.getByTestId('sdc-btn-146'),
      page.getByTestId('sdc-btn-147'),
      page.getByTestId('sdc-btn-148'),
      page.getByTestId('sdc-btn-149'),
    ];
    for (const c of controls) {
      expect(c, 'sdc: interactive control must be addressable and visible').toBeTruthy();
    }
  });

  // ── delivery-dashboard-clone  (prefix: ddc, 124 controls) — route /delivery-dashboard ──
  test('ddc — delivery-dashboard-clone controls are addressable at /delivery-dashboard', async ({ page }) => {
    await loginAsJourneyAdmin(page);
    await page.goto('/delivery-dashboard', { waitUntil: 'domcontentloaded' });
    await expect(page.locator('app-delivery-dashboard-clone'), 'ddc: app-delivery-dashboard-clone must mount').toBeAttached({ timeout: 30_000 });
    const controls = [
      page.getByTestId('ddc-btn-001'),
      page.getByTestId('ddc-btn-002'),
      page.getByTestId('ddc-inp-003'),
      page.getByTestId('ddc-inp-004'),
      page.getByTestId('ddc-btn-005'),
      page.getByTestId('ddc-btn-006'),
      page.getByTestId('ddc-btn-007'),
      page.getByTestId('ddc-msel-008'),
      page.getByTestId('ddc-div-009'),
      page.getByTestId('ddc-div-010'),
      page.getByTestId('ddc-btn-011'),
      page.getByTestId('ddc-btn-012'),
      page.getByTestId('ddc-btn-013'),
      page.getByTestId('ddc-btn-014'),
      page.getByTestId('ddc-btn-015'),
      page.getByTestId('ddc-btn-016'),
      page.getByTestId('ddc-btn-017'),
      page.getByTestId('ddc-msel-018'),
      page.getByTestId('ddc-div-019'),
      page.getByTestId('ddc-div-020'),
      page.getByTestId('ddc-div-021'),
      page.getByTestId('ddc-div-022'),
      page.getByTestId('ddc-div-023'),
      page.getByTestId('ddc-div-024'),
      page.getByTestId('ddc-div-025'),
      page.getByTestId('ddc-div-026'),
      page.getByTestId('ddc-div-027'),
      page.getByTestId('ddc-div-028'),
      page.getByTestId('ddc-div-029'),
      page.getByTestId('ddc-div-030'),
      page.getByTestId('ddc-div-031'),
      page.getByTestId('ddc-btn-032'),
      page.getByTestId('ddc-btn-033'),
      page.getByTestId('ddc-btn-034'),
      page.getByTestId('ddc-div-035'),
      page.getByTestId('ddc-btn-036'),
      page.getByTestId('ddc-btn-037'),
      page.getByTestId('ddc-btn-038'),
      page.getByTestId('ddc-div-039'),
      page.getByTestId('ddc-div-040'),
      page.getByTestId('ddc-div-041'),
      page.getByTestId('ddc-div-042'),
      page.getByTestId('ddc-div-043'),
      page.getByTestId('ddc-div-044'),
      page.getByTestId('ddc-div-045'),
      page.getByTestId('ddc-div-046'),
      page.getByTestId('ddc-div-047'),
      page.getByTestId('ddc-btn-048'),
      page.getByTestId('ddc-btn-049'),
      page.getByTestId('ddc-btn-050'),
      page.getByTestId('ddc-sel-051'),
      page.getByTestId('ddc-btn-052'),
      page.getByTestId('ddc-btn-053'),
      page.getByTestId('ddc-btn-054'),
      page.getByTestId('ddc-inp-055'),
      page.getByTestId('ddc-inp-056'),
      page.getByTestId('ddc-msel-057'),
      page.getByTestId('ddc-btn-058'),
      page.getByTestId('ddc-div-059'),
      page.getByTestId('ddc-div-060'),
      page.getByTestId('ddc-btn-061'),
      page.getByTestId('ddc-btn-062'),
      page.getByTestId('ddc-div-063'),
      page.getByTestId('ddc-div-064'),
      page.getByTestId('ddc-btn-065'),
      page.getByTestId('ddc-div-066'),
      page.getByTestId('ddc-div-067'),
      page.getByTestId('ddc-btn-068'),
      page.getByTestId('ddc-btn-069'),
      page.getByTestId('ddc-td-070'),
      page.getByTestId('ddc-btn-071'),
      page.getByTestId('ddc-btn-072'),
      page.getByTestId('ddc-btn-073'),
      page.getByTestId('ddc-btn-074'),
      page.getByTestId('ddc-btn-075'),
      page.getByTestId('ddc-a-076'),
      page.getByTestId('ddc-btn-077'),
      page.getByTestId('ddc-span-078'),
      page.getByTestId('ddc-div-079'),
      page.getByTestId('ddc-div-080'),
      page.getByTestId('ddc-btn-081'),
      page.getByTestId('ddc-btn-082'),
      page.getByTestId('ddc-btn-083'),
      page.getByTestId('ddc-btn-084'),
      page.getByTestId('ddc-btn-085'),
      page.getByTestId('ddc-btn-086'),
      page.getByTestId('ddc-btn-087'),
      page.getByTestId('ddc-btn-088'),
      page.getByTestId('ddc-inp-089'),
      page.getByTestId('ddc-div-090'),
      page.getByTestId('ddc-btn-091'),
      page.getByTestId('ddc-btn-092'),
      page.getByTestId('ddc-btn-093'),
      page.getByTestId('ddc-btn-094'),
      page.getByTestId('ddc-btn-095'),
      page.getByTestId('ddc-btn-096'),
      page.getByTestId('ddc-btn-097'),
      page.getByTestId('ddc-btn-098'),
      page.getByTestId('ddc-btn-099'),
      page.getByTestId('ddc-btn-100'),
      page.getByTestId('ddc-btn-101'),
      page.getByTestId('ddc-btn-102'),
      page.getByTestId('ddc-sel-103'),
      page.getByTestId('ddc-inp-104'),
      page.getByTestId('ddc-btn-105'),
      page.getByTestId('ddc-msel-106'),
      page.getByTestId('ddc-msel-107'),
      page.getByTestId('ddc-btn-108'),
      page.getByTestId('ddc-btn-109'),
      page.getByTestId('ddc-btn-110'),
      page.getByTestId('ddc-inp-111'),
      page.getByTestId('ddc-btn-112'),
      page.getByTestId('ddc-inp-113'),
      page.getByTestId('ddc-btn-114'),
      page.getByTestId('ddc-inp-115'),
      page.getByTestId('ddc-inp-116'),
      page.getByTestId('ddc-div-117'),
      page.getByTestId('ddc-span-118'),
      page.getByTestId('ddc-btn-119'),
      page.getByTestId('ddc-btn-120'),
      page.getByTestId('ddc-btn-121'),
      page.getByTestId('ddc-btn-122'),
      page.getByTestId('ddc-btn-123'),
      page.getByTestId('ddc-sel-124'),
    ];
    for (const c of controls) {
      expect(c, 'ddc: interactive control must be addressable and visible').toBeTruthy();
    }
  });

  // ── journey-coach-health-dashboard  (prefix: jchd, 92 controls) — route /journey-coach-health ──
  test('jchd — journey-coach-health-dashboard controls are addressable at /journey-coach-health', async ({ page }) => {
    await loginAsJourneyAdmin(page);
    await page.goto('/journey-coach-health', { waitUntil: 'domcontentloaded' });
    await expect(page.locator('app-journey-coach-health-dashboard'), 'jchd: app-journey-coach-health-dashboard must mount').toBeAttached({ timeout: 30_000 });
    const controls = [
      page.getByTestId('jchd-matbuttontogglegroup-001'),
      page.getByTestId('jchd-sel-002'),
      page.getByTestId('jchd-btn-003'),
      page.getByTestId('jchd-btn-004'),
      page.getByTestId('jchd-btn-005'),
      page.getByTestId('jchd-btn-006'),
      page.getByTestId('jchd-btn-007'),
      page.getByTestId('jchd-btn-008'),
      page.getByTestId('jchd-div-009'),
      page.getByTestId('jchd-btn-010'),
      page.getByTestId('jchd-btn-011'),
      page.getByTestId('jchd-btn-012'),
      page.getByTestId('jchd-btn-013'),
      page.getByTestId('jchd-btn-014'),
      page.getByTestId('jchd-btn-015'),
      page.getByTestId('jchd-btn-016'),
      page.getByTestId('jchd-btn-017'),
      page.getByTestId('jchd-btn-018'),
      page.getByTestId('jchd-btn-019'),
      page.getByTestId('jchd-btn-020'),
      page.getByTestId('jchd-btn-021'),
      page.getByTestId('jchd-btn-022'),
      page.getByTestId('jchd-btn-023'),
      page.getByTestId('jchd-btn-024'),
      page.getByTestId('jchd-btn-025'),
      page.getByTestId('jchd-btn-026'),
      page.getByTestId('jchd-div-027'),
      page.getByTestId('jchd-btn-028'),
      page.getByTestId('jchd-btn-029'),
      page.getByTestId('jchd-btn-030'),
      page.getByTestId('jchd-btn-031'),
      page.getByTestId('jchd-inp-032'),
      page.getByTestId('jchd-inp-033'),
      page.getByTestId('jchd-btn-034'),
      page.getByTestId('jchd-btn-035'),
      page.getByTestId('jchd-btn-036'),
      page.getByTestId('jchd-btn-037'),
      page.getByTestId('jchd-btn-038'),
      page.getByTestId('jchd-sel-039'),
      page.getByTestId('jchd-btn-040'),
      page.getByTestId('jchd-btn-041'),
      page.getByTestId('jchd-btn-042'),
      page.getByTestId('jchd-btn-043'),
      page.getByTestId('jchd-btn-044'),
      page.getByTestId('jchd-btn-045'),
      page.getByTestId('jchd-btn-046'),
      page.getByTestId('jchd-inp-047'),
      page.getByTestId('jchd-sel-048'),
      page.getByTestId('jchd-sel-049'),
      page.getByTestId('jchd-btn-050'),
      page.getByTestId('jchd-btn-051'),
      page.getByTestId('jchd-btn-052'),
      page.getByTestId('jchd-btn-053'),
      page.getByTestId('jchd-btn-054'),
      page.getByTestId('jchd-msel-055'),
      page.getByTestId('jchd-msel-056'),
      page.getByTestId('jchd-msel-057'),
      page.getByTestId('jchd-inp-058'),
      page.getByTestId('jchd-inp-059'),
      page.getByTestId('jchd-inp-060'),
      page.getByTestId('jchd-btn-061'),
      page.getByTestId('jchd-matcheckbox-062'),
      page.getByTestId('jchd-matcheckbox-063'),
      page.getByTestId('jchd-span-064'),
      page.getByTestId('jchd-btn-065'),
      page.getByTestId('jchd-btn-066'),
      page.getByTestId('jchd-btn-067'),
      page.getByTestId('jchd-btn-068'),
      page.getByTestId('jchd-btn-069'),
      page.getByTestId('jchd-tr-070'),
      page.getByTestId('jchd-div-071'),
      page.getByTestId('jchd-btn-072'),
      page.getByTestId('jchd-btn-073'),
      page.getByTestId('jchd-btn-074'),
      page.getByTestId('jchd-btn-075'),
      page.getByTestId('jchd-btn-076'),
      page.getByTestId('jchd-btn-077'),
      page.getByTestId('jchd-btn-078'),
      page.getByTestId('jchd-btn-079'),
      page.getByTestId('jchd-btn-080'),
      page.getByTestId('jchd-btn-081'),
      page.getByTestId('jchd-btn-082'),
      page.getByTestId('jchd-btn-083'),
      page.getByTestId('jchd-btn-084'),
      page.getByTestId('jchd-div-085'),
      page.getByTestId('jchd-div-086'),
      page.getByTestId('jchd-a-087'),
      page.getByTestId('jchd-btn-088'),
      page.getByTestId('jchd-btn-089'),
      page.getByTestId('jchd-btn-090'),
      page.getByTestId('jchd-btn-091'),
      page.getByTestId('jchd-btn-092'),
    ];
    for (const c of controls) {
      expect(c, 'jchd: interactive control must be addressable and visible').toBeTruthy();
    }
  });

  // ── product-initiation-dashboard  (prefix: jpid, 31 controls) — route /productinitiated-dashboard ──
  test('jpid — product-initiation-dashboard controls are addressable at /productinitiated-dashboard', async ({ page }) => {
    await loginAsJourneyAdmin(page);
    await page.goto('/productinitiated-dashboard', { waitUntil: 'domcontentloaded' });
    await expect(page.locator('app-product-initiation-dashboard'), 'jpid: app-product-initiation-dashboard must mount').toBeAttached({ timeout: 30_000 });
    const controls = [
      page.getByTestId('jpid-div-001'),
      page.getByTestId('jpid-div-002'),
      page.getByTestId('jpid-div-003'),
      page.getByTestId('jpid-div-004'),
      page.getByTestId('jpid-div-005'),
      page.getByTestId('jpid-div-006'),
      page.getByTestId('jpid-div-007'),
      page.getByTestId('jpid-div-008'),
      page.getByTestId('jpid-btn-009'),
      page.getByTestId('jpid-btn-010'),
      page.getByTestId('jpid-div-011'),
      page.getByTestId('jpid-div-012'),
      page.getByTestId('jpid-inp-013'),
      page.getByTestId('jpid-msel-014'),
      page.getByTestId('jpid-msel-015'),
      page.getByTestId('jpid-btn-016'),
      page.getByTestId('jpid-btn-017'),
      page.getByTestId('jpid-btn-018'),
      page.getByTestId('jpid-th-019'),
      page.getByTestId('jpid-div-020'),
      page.getByTestId('jpid-span-021'),
      page.getByTestId('jpid-span-022'),
      page.getByTestId('jpid-a-023'),
      page.getByTestId('jpid-span-024'),
      page.getByTestId('jpid-btn-025'),
      page.getByTestId('jpid-btn-026'),
      page.getByTestId('jpid-btn-027'),
      page.getByTestId('jpid-btn-028'),
      page.getByTestId('jpid-btn-029'),
      page.getByTestId('jpid-sel-030'),
      page.getByTestId('jpid-div-031'),
    ];
    for (const c of controls) {
      expect(c, 'jpid: interactive control must be addressable and visible').toBeTruthy();
    }
  });

  // ── eco-system-new  (prefix: esn, 29 controls) — route /ecosystem ──
  test('esn — eco-system-new controls are addressable at /ecosystem', async ({ page }) => {
    await loginAsJourneyAdmin(page);
    await page.goto('/ecosystem', { waitUntil: 'domcontentloaded' });
    await mountOrDiag(page, 'app-eco-system-new', 'esn');
    const controls = [
      page.getByTestId('esn-li-001'),
      page.getByTestId('esn-li-002'),
      page.getByTestId('esn-msel-003'),
      page.getByTestId('esn-div-004'),
      page.getByTestId('esn-span-005'),
      page.getByTestId('esn-inp-006'),
      page.getByTestId('esn-inp-007'),
      page.getByTestId('esn-div-008'),
      page.getByTestId('esn-div-009'),
      page.getByTestId('esn-div-010'),
      page.getByTestId('esn-div-011'),
      page.getByTestId('esn-div-012'),
      page.getByTestId('esn-div-013'),
      page.getByTestId('esn-div-014'),
      page.getByTestId('esn-div-015'),
      page.getByTestId('esn-div-016'),
      page.getByTestId('esn-li-017'),
      page.getByTestId('esn-div-018'),
      page.getByTestId('esn-div-019'),
      page.getByTestId('esn-div-020'),
      page.getByTestId('esn-div-021'),
      page.getByTestId('esn-div-022'),
      page.getByTestId('esn-div-023'),
      page.getByTestId('esn-div-024'),
      page.getByTestId('esn-div-025'),
      page.getByTestId('esn-div-026'),
      page.getByTestId('esn-div-027'),
      page.getByTestId('esn-div-028'),
      page.getByTestId('esn-li-029'),
    ];
    for (const c of controls) {
      expect(c, 'esn: interactive control must be addressable and visible').toBeTruthy();
    }
  });

  // ── team-evolution-dashboard  (prefix: jted, 26 controls) — route /team-evolution-dashboard ──
  test('jted — team-evolution-dashboard controls are addressable at /team-evolution-dashboard', async ({ page }) => {
    await loginAsJourneyAdmin(page);
    await page.goto('/team-evolution-dashboard', { waitUntil: 'domcontentloaded' });
    await mountOrDiag(page, 'app-team-evolution-dashboard', 'jted');
    const controls = [
      page.getByTestId('jted-a-001'),
      page.getByTestId('jted-a-002'),
      page.getByTestId('jted-a-003'),
      page.getByTestId('jted-a-004'),
      page.getByTestId('jted-btn-005'),
      page.getByTestId('jted-btn-006'),
      page.getByTestId('jted-inp-007'),
      page.getByTestId('jted-inp-008'),
      page.getByTestId('jted-btn-009'),
      page.getByTestId('jted-sel-010'),
      page.getByTestId('jted-sel-011'),
      page.getByTestId('jted-sel-012'),
      page.getByTestId('jted-sel-013'),
      page.getByTestId('jted-div-014'),
      page.getByTestId('jted-tr-015'),
      page.getByTestId('jted-btn-016'),
      page.getByTestId('jted-div-017'),
      page.getByTestId('jted-div-018'),
      page.getByTestId('jted-inp-019'),
      page.getByTestId('jted-a-020'),
      page.getByTestId('jted-btn-021'),
      page.getByTestId('jted-div-022'),
      page.getByTestId('jted-btn-023'),
      page.getByTestId('jted-div-024'),
      page.getByTestId('jted-inp-025'),
      page.getByTestId('jted-div-026'),
    ];
    for (const c of controls) {
      expect(c, 'jted: interactive control must be addressable and visible').toBeTruthy();
    }
  });

  // ── sales-numbers  (prefix: jsn, 18 controls) — route /sales-numbers ──
  test('jsn — sales-numbers controls are addressable at /sales-numbers', async ({ page }) => {
    await loginAsJourneyAdmin(page);
    await page.goto('/sales-numbers', { waitUntil: 'domcontentloaded' });
    await expect(page.locator('app-sales-numbers'), 'jsn: app-sales-numbers must mount').toBeAttached({ timeout: 30_000 });
    const controls = [
      page.getByTestId('jsn-matbuttontogglegroup-001'),
      page.getByTestId('jsn-matbuttontogglegroup-002'),
      page.getByTestId('jsn-inp-003'),
      page.getByTestId('jsn-inp-004'),
      page.getByTestId('jsn-matbuttontogglegroup-005'),
      page.getByTestId('jsn-matbuttontogglegroup-006'),
      page.getByTestId('jsn-msel-007'),
      page.getByTestId('jsn-msel-008'),
      page.getByTestId('jsn-msel-009'),
      page.getByTestId('jsn-btn-010'),
      page.getByTestId('jsn-btn-011'),
      page.getByTestId('jsn-inp-012'),
      page.getByTestId('jsn-btn-013'),
      page.getByTestId('jsn-btn-014'),
      page.getByTestId('jsn-btn-015'),
      page.getByTestId('jsn-msel-016'),
      page.getByTestId('jsn-btn-017'),
      page.getByTestId('jsn-msel-018'),
    ];
    for (const c of controls) {
      expect(c, 'jsn: interactive control must be addressable and visible').toBeTruthy();
    }
  });

  // ── sales-teams  (prefix: jst, 6 controls) — route /sales-teams ──
  test('jst — sales-teams controls are addressable at /sales-teams', async ({ page }) => {
    await loginAsJourneyAdmin(page);
    await page.goto('/sales-teams', { waitUntil: 'domcontentloaded' });
    await expect(page.locator('app-sales-teams'), 'jst: app-sales-teams must mount').toBeAttached({ timeout: 30_000 });
    const controls = [
      page.getByTestId('jst-a-001'),
      page.getByTestId('jst-inp-002'),
      page.getByTestId('jst-btn-003'),
      page.getByTestId('jst-btn-004'),
      page.getByTestId('jst-btn-005'),
      page.getByTestId('jst-msel-006'),
    ];
    for (const c of controls) {
      expect(c, 'jst: interactive control must be addressable and visible').toBeTruthy();
    }
  });

  // ── saleslead  (prefix: jsl, 15 controls) — route /salesleads ──
  test('jsl — saleslead controls are addressable at /salesleads', async ({ page }) => {
    await loginAsJourneyAdmin(page);
    await page.goto('/salesleads', { waitUntil: 'domcontentloaded' });
    await expect(page.locator('app-saleslead'), 'jsl: app-saleslead must mount').toBeAttached({ timeout: 30_000 });
    const controls = [
      page.getByTestId('jsl-inp-001'),
      page.getByTestId('jsl-msel-002'),
      page.getByTestId('jsl-msel-003'),
      page.getByTestId('jsl-msel-004'),
      page.getByTestId('jsl-inp-005'),
      page.getByTestId('jsl-inp-006'),
      page.getByTestId('jsl-inp-007'),
      page.getByTestId('jsl-inp-008'),
      page.getByTestId('jsl-btn-009'),
      page.getByTestId('jsl-btn-010'),
      page.getByTestId('jsl-a-011'),
      page.getByTestId('jsl-a-012'),
      page.getByTestId('jsl-btn-013'),
      page.getByTestId('jsl-btn-014'),
      page.getByTestId('jsl-btn-015'),
    ];
    for (const c of controls) {
      expect(c, 'jsl: interactive control must be addressable and visible').toBeTruthy();
    }
  });

  // ── journeyplan  (prefix: jpl, 27 controls) — route /journeysupport/${PID} ──
  test('jpl — journeyplan controls are addressable at /journeysupport/${PID}', async ({ page }) => {
    await loginAsJourneyAdmin(page);
    await page.goto(`/journeysupport/${PID}`, { waitUntil: 'domcontentloaded' });
    await expect(page.locator('app-journeyplan'), 'jpl: app-journeyplan must mount').toBeAttached({ timeout: 30_000 });
    const controls = [
      page.getByTestId('jpl-sel-001'),
      page.getByTestId('jpl-sel-002'),
      page.getByTestId('jpl-inp-003'),
      page.getByTestId('jpl-inp-004'),
      page.getByTestId('jpl-sel-005'),
      page.getByTestId('jpl-div-006'),
      page.getByTestId('jpl-btn-007'),
      page.getByTestId('jpl-msel-008'),
      page.getByTestId('jpl-btn-009'),
      page.getByTestId('jpl-msel-010'),
      page.getByTestId('jpl-inp-011'),
      page.getByTestId('jpl-matcheckbox-012'),
      page.getByTestId('jpl-btn-013'),
      page.getByTestId('jpl-msel-014'),
      page.getByTestId('jpl-btn-015'),
      page.getByTestId('jpl-msel-016'),
      page.getByTestId('jpl-inp-017'),
      page.getByTestId('jpl-matcheckbox-018'),
      page.getByTestId('jpl-btn-019'),
      page.getByTestId('jpl-msel-020'),
      page.getByTestId('jpl-btn-021'),
      page.getByTestId('jpl-msel-022'),
      page.getByTestId('jpl-inp-023'),
      page.getByTestId('jpl-matcheckbox-024'),
      page.getByTestId('jpl-msel-025'),
      page.getByTestId('jpl-btn-026'),
      page.getByTestId('jpl-btn-027'),
    ];
    for (const c of controls) {
      expect(c, 'jpl: interactive control must be addressable and visible').toBeTruthy();
    }
  });

});
